import { createStore } from "vuex";

export default createStore({
  state: {
    copySuccess: false,
    copyError: false,
    user: {
      name: "Emirhan Pala",
      email: "emrhnpla02@protonmail.com",
      about: "just a 16yo teenager",
    },
    links: [
      {
        websiteIcon: "fab fa-github",
        websiteIconColor: "#303443",
        websiteHref: "https://www.github.com",
        websiteName: "GitHub",
        userHref: "https://github.com/emrhnpla02",
        username: "emrhnpla02",
        isBased: true,
      },
      {
        websiteIcon: "fab fa-gitlab",
        websiteIconColor: "#FC7938",
        websiteHref: "https://www.gitlab.com",
        websiteName: "GitLab",
        userHref: "https://gitlab.com/emrhnpla02",
        username: "emrhnpla02",
        isBased: true,
      },
      {
        websiteIcon: "fas fa-paw",
        websiteIconColor: "#000000",
        websiteHref: "https://lemmy.ml/",
        websiteName: "Lemmy",
        userHref: "https://lemmy.ml/u/emrhnpla02",
        username: "emrhnpla02",
        isBased: true,
      },
      {
        websiteIcon: "fab fa-mastodon",
        websiteIconColor: "#3088D4",
        websiteHref: "https://mastodon.social/web/home",
        websiteName: "Mastodon",
        userHref: "https://mastodon.social/web/@emrhnpla02",
        username: "@emrhnpla02@mastodon.social",
        isBased: true,
      },
      {
        websiteIcon: "fab fa-steam",
        websiteIconColor: "#177ECA",
        websiteHref: "https://store.steampowered.com/",
        websiteName: "Steam",
        userHref: "https://steamcommunity.com/id/emrhnpla02/",
        username: "emrhnpla02",
        isBased: false,
      },
      {
        websiteIcon: " fab fa-spotify",
        websiteIconColor: "#1CAE51",
        websiteHref: "https://www.spotify.com/",
        websiteName: "Spotify",
        userHref: "https://open.spotify.com/user/8s8mxqnkzgqak32l7tcnuzhs2",
        username: "emrhnpla02",
        isBased: false,
      },
      {
        websiteIcon: "fab fa-medium-m",
        websiteIconColor: "#000000",
        websiteHref: "https://matrix.org/",
        websiteName: "Matrix",
        userHref: "https://matrix.to/#/@emrhnpla02:matrix.org",
        username: "@emrhnpla02",
        isBased: true,
      },
    ],
  },
});
